{"name": "login with valid and invalid user -- @1.2 ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//span[@class='title']\"}\n  (Session info: chrome=114.0.5735.199); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x006F8893+48451]\n\t(No symbol) [0x0068B8A1]\n\t(No symbol) [0x00595058]\n\t(No symbol) [0x005C0467]\n\t(No symbol) [0x005C069B]\n\t(No symbol) [0x005EDD92]\n\t(No symbol) [0x005DA304]\n\t(No symbol) [0x005EC482]\n\t(No symbol) [0x005DA0B6]\n\t(No symbol) [0x005B7E08]\n\t(No symbol) [0x005B8F2D]\n\tGetHandleVerifier [0x00958E3A+2540266]\n\tGetHandleVerifier [0x00998959+2801161]\n\tGetHandleVerifier [0x0099295C+2776588]\n\tGetHandleVerifier [0x00782280+612144]\n\t(No symbol) [0x00694F6C]\n\t(No symbol) [0x006911D8]\n\t(No symbol) [0x006912BB]\n\t(No symbol) [0x00684857]\n\tBaseThreadInitThunk [0x774200C9+25]\n\tRtlGetAppContainerNamedObjectPath [0x77967B4E+286]\n\tRtlGetAppContainerNamedObjectPath [0x77967B1E+238]\n\n", "trace": "  File \"c:\\users\\dell\\pycharmprojects\\behavesaucedemo\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\dell\\pycharmprojects\\behavesaucedemo\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"feature\\steps\\login.py\", line 34, in verify\n    te = context.driver.find_element(By.XPATH, \"//span[@class='title']\").text\n  File \"c:\\users\\dell\\pycharmprojects\\behavesaucedemo\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 740, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"c:\\users\\dell\\pycharmprojects\\behavesaucedemo\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\dell\\pycharmprojects\\behavesaucedemo\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given launch chrome browser", "status": "passed", "start": 1689692171856, "stop": 1689692173636}, {"name": "When open url \"https://www.saucedemo.com/\"", "status": "passed", "start": 1689692173637, "stop": 1689692175286}, {"name": "And wait for some period", "status": "passed", "start": 1689692175286, "stop": 1689692175289}, {"name": "And enter username \"locked_out_user\" and password  \"secret_sauce\"", "status": "passed", "start": 1689692175289, "stop": 1689692175538}, {"name": "And click on login button", "status": "passed", "start": 1689692175538, "stop": 1689692175630}, {"name": "Then user verify title", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//span[@class='title']\"}\n  (Session info: chrome=114.0.5735.199); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x006F8893+48451]\n\t(No symbol) [0x0068B8A1]\n\t(No symbol) [0x00595058]\n\t(No symbol) [0x005C0467]\n\t(No symbol) [0x005C069B]\n\t(No symbol) [0x005EDD92]\n\t(No symbol) [0x005DA304]\n\t(No symbol) [0x005EC482]\n\t(No symbol) [0x005DA0B6]\n\t(No symbol) [0x005B7E08]\n\t(No symbol) [0x005B8F2D]\n\tGetHandleVerifier [0x00958E3A+2540266]\n\tGetHandleVerifier [0x00998959+2801161]\n\tGetHandleVerifier [0x0099295C+2776588]\n\tGetHandleVerifier [0x00782280+612144]\n\t(No symbol) [0x00694F6C]\n\t(No symbol) [0x006911D8]\n\t(No symbol) [0x006912BB]\n\t(No symbol) [0x00684857]\n\tBaseThreadInitThunk [0x774200C9+25]\n\tRtlGetAppContainerNamedObjectPath [0x77967B4E+286]\n\tRtlGetAppContainerNamedObjectPath [0x77967B1E+238]\n\n", "trace": "  File \"c:\\users\\dell\\pycharmprojects\\behavesaucedemo\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\dell\\pycharmprojects\\behavesaucedemo\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"feature\\steps\\login.py\", line 34, in verify\n    te = context.driver.find_element(By.XPATH, \"//span[@class='title']\").text\n  File \"c:\\users\\dell\\pycharmprojects\\behavesaucedemo\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 740, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"c:\\users\\dell\\pycharmprojects\\behavesaucedemo\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\dell\\pycharmprojects\\behavesaucedemo\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1689692175630, "stop": 1689692195665}, {"name": "And close browser", "status": "skipped", "start": 1689692195666, "stop": 1689692195666}], "parameters": [{"name": "username", "value": "locked_out_user"}, {"name": "password", "value": "secret_sauce"}], "start": 1689692171855, "stop": 1689692195666, "uuid": "4d2885cc-e167-490c-94f7-e15c7ca10d25", "historyId": "92ccfd20236fb20691ce17076c9b80f1", "fullName": "login saucedemo: login with valid and invalid user", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "login saucedemo"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}